import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
    {
    id: "kwS_MffzqLw",
    video_title: "Motion Graphics Video Editing – Promotional Social Media Design",
    video_description: `This project was created using modern motion graphics techniques to produce an attractive and professional promotional video.`,
    tags: [
      
    ],
    cover_image: "kwS_MffzqLw",
    publish_date: "2024-01-19",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback:
      "",
    video_link: "https://youtube.com/shorts/kwS_MffzqLw?feature=share",
    project_images: [],
    category: ["Motion Graphics","Shorts"],
    duration: "2:43",
    software_used: ["premiere pro"],
  },
  {
    id: "3w8afAnULzg",
    video_title: "The Art of Documentary Storytelling",
    video_description: `A cinematic documentary-style edit focused on authentic storytelling, emotional pacing, and professional post-production quality.`,
    tags: [],
    cover_image: "3w8afAnULzg",
    publish_date: "2024-08-04",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/3w8afAnULzg",
    project_images: [],
    category: ["Documentary", "Promo"],
    duration: "21:00",
    software_used: ["premiere pro"],
  },
  {
    id: "Q0VGycA5PEY",
    video_title: "Commercial Restoration Video Edit",
    video_description:
      "This video was edited for NexPhase Restoration, showcasing their professional restoration services with a clean and impactful visual storytelling approach.",
    tags: [],
    cover_image: "Q0VGycA5PEY",
    publish_date: "2024-04-08",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/Q0VGycA5PEY?feature=share",
    project_images: [],
    category: ["Caption Editing ", "Talking Head" , "Shorts"],
    duration: "10:12",
    software_used: ["premiere pro"],
  },
  {
    id: "cBytKoUGjYQ",
    video_title:
      "Beat Sync Clip Cut Shorts – Social Media Video Edit",
    video_description: `This project was created for NexPhase Restoration as a short-form promotional video using beat-synced clip cutting technique.`,
    tags: [],
    cover_image: "cBytKoUGjYQ",
    publish_date: "2025-06-06",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/cBytKoUGjYQ?feature=share",
    project_images: [],
    category: ["Shorts"],
    duration: "7:18",
    software_used: ["premiere pro"],
  },
  {
    id: "_bEdjXi_yjQ",
    video_title:
      "Beat Sync Clip Cut Shorts – Social Media Video Edit",
    video_description: `This project was created for NexPhase Restoration as a short-form promotional video using beat-synced clip cutting technique.`,
    tags: [],
    cover_image: "_bEdjXi_yjQ",
    publish_date: "2025-06-20",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/_bEdjXi_yjQ?feature=share",
    project_images: [],
    category: ["Shorts"],
    duration: "8:13",
    software_used: ["premiere pro"],
  },
  {
    id: "t_fAwNueIns",
    video_title: "Beat Fast Pace Clip Cut Marketing Shorts – Instagram Reel Edit",
    video_description: `This project was created for NexPhase Restoration as a short-form promotional video using beat-synced clip cutting technique.`,
    tags: [],
    cover_image: "t_fAwNueIns",
    publish_date: "2025-07-11",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/t_fAwNueIns?feature=share",
    project_images: [],
    category: ["Shorts"],
    duration: "7:59",
    software_used: ["premiere pro"],
  },
  {
    id: "Adws0wuslQo",
    video_title: "Beat Social Media Visual Edit – Motion Graphics & Caption Integration",
    video_description:
      "This project is a short-form social media video edit focusing on visual enhancement, animated captions, and motion graphics integration.",
    tags: [],
    cover_image: "Adws0wuslQo",
    publish_date: "2024-01-16",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/Adws0wuslQo?feature=share",
    project_images: [],
    category: ["Caption Editing ", "Talking Head" , "Shorts"],
    duration: "2:44",
    software_used: ["premiere pro"],
  },
  // end.................................................................
  {
    id: "xbGKJtHuyBc",
    video_title: "Beat Music Beat Transition Shorts – Promotional Video Editing ",
    video_description:
      "This project was created for NexPhase Restoration as a short-form promotional video using beat-synced clip cutting technique.",
    tags: [],
    cover_image: "xbGKJtHuyBc",
    publish_date: "2025-02-27",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/xbGKJtHuyBc?feature=share",
    project_images: [],
    category: ["Shorts"],
    duration: "1:10",
    software_used: ["premiere pro"],
  },
  {
    id: "LuhmyAHCaq8",
    video_title: "Beat Dynamic Beat Match Social Media Shorts – Service Marketing Reel",
    video_description:
      "This project was created for NexPhase Restoration as a short-form promotional video using beat-synced clip cutting technique.",
    tags: [],
    cover_image: "LuhmyAHCaq8",
    publish_date: "2025-03-05",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/LuhmyAHCaq8?feature=share",
    project_images: [],
    category: ["Shorts"],
    duration: "1:24",
    software_used: ["premiere pro"],
  },
  {
    id: "hNbNtH0g31s",
    video_title: "Caption Editing – Social Media Promotional Video",
    video_description:
      "This project was created for NexPhase Restoration, focusing on professional caption editing to improve audience understanding and engagement.",
    tags: [],
    cover_image: "hNbNtH0g31s",
    publish_date: "2025-03-06",
    client_name: "Eco Farming",
    client_image: "/companies/Ecofarming.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/hNbNtH0g31s?feature=share",
    project_images: [],
    category: ["Caption Editing " , "Shorts"],
    duration: "1:11",
    software_used: ["premiere pro"],
  },
  {
    id: "6FeIMt9vNq8",
    video_title: "Promotional Caption Design – Social Media Video Edit",
    video_description:
      "This project was created for NexPhase Restoration, focusing on professional promotional caption editing to enhance video communication and viewer engagement.",
    tags: [],
    cover_image: "6FeIMt9vNq8",
    publish_date: "2025-03-06",
    client_name: "Eco Farming",
    client_image: "/companies/Ecofarming.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/6FeIMt9vNq8?feature=share",
    project_images: [],
    category: ["Caption Editing ", "Talking Head" , "Shorts"],
    duration: "1:09",
    software_used: ["premiere pro"],
  },
  {
    id: "xaBwgdshaP4",
    video_title: "Promotional Caption Design – Social Media Video Edit",
    video_description:
      "This project was created for promotional purposes, focusing on highlighting additional service content through professional video editing.",
    tags: [],
    cover_image: "xaBwgdshaP4",
    publish_date: "2025-03-07",
    client_name: "Eco Farming",
    client_image: "/companies/Ecofarming.png",
    client_feedback: "",
    video_link: "//youtube.com/shorts/xaBwgdshaP4?feature=share",
    project_images: [],
    category: ["Caption Editing ", "Motion Graphics" , "Talking Head" , "Shorts"  ],
    duration: "1:21",
    software_used: ["premiere pro"],
  },
  {
    id: "Rb7Rkb5V3lI",
    video_title: "Add Service Promotional Video – Social Media Edit",
    video_description: "This project was created for promotional purposes, focusing on highlighting additional service content through professional video editing.",
    tags: [
     
    ],
    cover_image: "Rb7Rkb5V3lI",
    publish_date: "2024-02-01",
    client_name: "Edu Bridge Academy",
    client_image: "/companies/edu-bridge-academy.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/Rb7Rkb5V3lI?feature=share",
    project_images: [],
    category: [ "Talking Head" , "Shorts"],
    duration: "1:28",
    software_used: ["premiere pro"],
  },
  {
    id: "NL1KZkqoXRE",
    video_title:
      "B-Roll Promotional Video Editing – Voiceover Based Social Media Content",
    video_description: `This project was created using professional B-roll video editing techniques combined with voiceover-based storytelling to deliver a clear and engaging promotional message.`,
    tags: [],
    cover_image: "NL1KZkqoXRE",
    publish_date: "2025-01-19",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/NL1KZkqoXRE?feature=share",
    project_images: [],
    category: ["Story telling" , "Shorts"],
    duration: "1:29",
    software_used: ["Capcut"],
  },
  {
    id: "TDByOqyscmY",
    video_title: "Voiceover B-Roll Social Media Promo – Short Form Video Editing",
    video_description:
      "This project was designed using professional voiceover-based B-roll editing to create an engaging short-form promotional video.",
    tags: [],
    cover_image: "TDByOqyscmY",
    publish_date: "2024-04-12",
    client_name: "EcoRevolution",
    client_image: "/companies/eco-revolution.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/TDByOqyscmY?feature=share",
    project_images: [],
    category: ["Story telling" , "Shorts"],
    duration: "3:51",
    software_used: ["Capcut"],
  },
  {
    id: "BIV-nro-MW8",
    video_title: "Motion Graphics & Caption Design – Promotional Social Media Video Editing",
    video_description: `This project combines professional motion graphics and caption editing to create an engaging promotional social media video.`,
    tags: [],
    cover_image: "BIV-nro-MW8",
    publish_date: "2025-07-23",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/BIV-nro-MW8?feature=share",
    project_images: [],
    category: ["Motion Graphics" , "Talking Head" , "Shorts"],
    duration: "1:28",
    software_used: ["premiere pro"],
  },
]
